replicaCount: 1

namespace: papishares

image:
  repository: ophintor/papishares
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

containerPort: 5000

probes:
  enabled: false

readinessProbe:
  path: /health
  port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2

livenessProbe:
  path: /health
  post: 5000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
  enabled: true
  name: papishares-secrets

ingress:
  enabled: true
  className: nginx
  annotations:
      cert-manager.io/cluster-issuer: ca-issuer
  hosts:
    - host: papishares.papichulo
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - papishares.papichulo
      secretName: papishares-tls

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 5
  # targetCPUUtilizationPercentage: 80

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

env: {}
extraEnv: []
