{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  T212_API_KEY: {{ .Values.env.t212_api_key }}
  T212_SECRET_KEY: {{ .Values.env.t212_secret_key }}
  T212_API_BASE: {{ .Values.env.t212_api_base }}
  TELEGRAM_BOT_TOKEN: {{ .Values.env.telegram_bot_token }}
  TELEGRAM_CHAT_ID: {{ .Values.env.telegram_chat_id }}
{{- end }}
