{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  API_KEY: {{ .Values.env.api_key }}
  API_BASE: {{ .Values.env.api_base }}
  BOT_TOKEN: {{ .Values.env.bot_token }}
  CHAT_ID: {{ .Values.env.chat_id }}
{{- end }}
